export const GeradoresEnergiaList = [
  {
    id: 0,
    valor: 200,
    quantidadeGerada: 450,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }, {
    id: 1,
    valor: 650,
    quantidadeGerada: 750,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }, {
    id: 2,
    valor: 1250,
    quantidadeGerada: 1450,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }, {
    id: 3,
    valor: 2850,
    quantidadeGerada: 2190,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }, {
    id: 4,
    valor: 4220,
    quantidadeGerada: 3890,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }, {
    id: 5,
    valor: 13490,
    quantidadeGerada: 4990,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }, {
    id: 6,
    valor: 23490,
    quantidadeGerada: 6750,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }, {
    id: 7,
    valor: 45730,
    quantidadeGerada: 8980,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }, {
    id: 8,
    valor: 256650,
    quantidadeGerada: 26980,
    quantidadeTotal: 0,
    quantidadeAtiva: 0,
  }
]